# Generated by Django 3.1.4 on 2021-02-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=20)),
                ('Item_price', models.FloatField()),
                ('Item_image', models.ImageField(upload_to='Myapp/static')),
            ],
        ),
    ]
