# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-03-06 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_newitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Price', models.FloatField()),
                ('Quatity', models.IntegerField()),
                ('Total', models.FloatField()),
            ],
        ),
    ]
